### ISSUE TITLE
Deleted product results in browser redirect loop.

### ISSUE THREAD

**Issue by lat9** [lat9/usu#42]
... as reported in [this](https://www.zen-cart.com/showthread.php?199064-Ultimate-SEO-v3-(and-v2-200)-Support-Thread&p=1380006) Zen Cart support-thread posting.  Results in the following message on FireFox:
![image](https://user-images.githubusercontent.com/2685585/115145307-dbadde00-a01e-11eb-8ab6-877934c98648.png)

**Comment by lat9** [comment]
Please refer to follow-on posts for that support-thread posting for an analysis of 'what went wrong'.

**Comment by jodsclass** [comment]
Thanks lat9.

Invalid or deleted product ids are now redirecting to the product not found page & sending a 404.

One problem is, old urls aren't rewriting to new ones. For example if originally my product was named and available at https://www.koolbadges.co.uk/japanes...es-p-3121.html but after being renamed is now at https://www.koolbadges.co.uk/cute-bl...es-p-3121.html with the rewrite I would expect the old url to redirect to the new to reflect the name change, however both urls are returning a 200 response and are valid. 

Also, not sure why, but because of the way ZC is redirecting, a deleted URL will show a 302 before a 404. In the search console on deleted products, when manually testing the url, it still says redirect loop with google bot.

Example URL on our website of deleted product is https://www.koolbadges.co.uk/red-treble-clef-badge-p-4881.html
But response by google bot is still as follows

![Screenshot 2021-04-19 at 07 27 34](https://user-images.githubusercontent.com/57923781/115191042-69013900-a0d8-11eb-95ae-e4032edf430c.png)

**Comment by lat9** [comment]
Thanks for that!  With the current 'restructuring', I'll update the usu base-class so that it doesn't do its redirect if the canonical link has not yet been set.  That will correct the 302 => 404 transition that google is complaining about and the now-deleted products' URLs will be of the 'standard' Zen Cart format, e.g. `index.php?main_page=product_info&products_id=77`.

It's not good (for me) to mix different issues in a single GitHub issue, so I'll pull your other query out into a separate one.

**Comment by lat9** [comment]
> Also, not sure why, but because of the way ZC is redirecting, a deleted URL will show a 302 before a 404. In the search console on deleted products, when manually testing the url, it still says redirect loop with google bot.
> 
Noting that this 302->404 behavior is (right, wrong or indifferent) the standard Zen Cart behavior for a URL that contains a `products_id` variable whose value is not registered within the site's database.

**Comment by jodsclass** [comment]
That seems to be an issue as google doesn't seem to follow a 302 to a 404. With a 302-> 404 googlebot will still claim there is a redirection loop, possibly because you are telling the bot that the url is temporarily a 404 which is a permanent removal. I guess a temporary redirect and a permanent removal (404) are incompatible with google logic.

Using the change mentioned over on the forum by carlwhat to init_sanitize.php and version 3.0.8 of USU throws a 301 -> 404 which googlebot can parse when viewing a deleted/non-existent product.

**Comment by jodsclass** [comment]
Top picture is using the beta USU, googlebot will still show a redirect loop. Bottom picture is using version 3.0.8 of USU and the commented out line to init_santize.php mentioned over on the forum.

As you can see, the top one shows a redirect loop while the bottom reports the 404 correctly. Both tests on the same deleted product.
![Screenshot 2021-04-19 at 18 59 37](https://user-images.githubusercontent.com/57923781/115281997-3176a900-a139-11eb-925e-ab8717b1a040.png)

![Screenshot 2021-04-19 at 18 59 52](https://user-images.githubusercontent.com/57923781/115282092-4c491d80-a139-11eb-961d-278172efeed5.png)

**Comment by lat9** [comment]
That change just 'pushed' now checks that the submitted URL parameters are valid prior to issuing any redirect.  That is, 
- An invalid `products_id` on a storefront access.
   - Note that a valid `products_id` with an invalid (or 'unlinked') cPath parameter will result in a 301 redirect using the product's defined 'master_categories_id'.
- An invalid `cPath` on a storefront access to the `index` page.
- An invalid `manufacturers_id` on a storefront access to the `index` page.
- An invalid EZ-Pages `id` on a storefront access to the `page` page.

If any of those conditions is found, the submitted URL with invalid parameters will not be redirected and the 'base' Zen Cart processing will take over.  Noting that some anomalies will be present:

1. An invalid EZ-Pages 'id' results in a 302 redirect, transitioning to the home page with a 200 status.
2. An invalid products_id results (using the 'as shipped' init_sanitize.php) in a 302 redirect to the product_info page with the invalid products_id
3. An invalid products_id results (using the commented-out version of init_sanitize.php) results in an unmodified URI that results in a 404.  The canonical link is provided by the base Zen Cart's formatting, referencing the product_info page with the invalid products_id.

That 'commented-out' section of `/includes/init_includes/init_sanitize.php` looks similar to the following (YMMV based on the Zen Cart version in use):

```php
/**
 * validate products_id for search engines and bookmarks, etc.
 */
  if (isset($_GET['products_id']) && isset($_SESSION['check_valid']) &&  $_SESSION['check_valid'] != 'false') {
    $check_valid = zen_products_id_valid($_GET['products_id']);
    if (!$check_valid) {
      $_GET['main_page'] = zen_get_info_page($_GET['products_id']);
      //
      // do not recheck redirect
      //
      $_SESSION['check_valid'] = 'false';
      zen_redirect(zen_href_link($_GET['main_page'], 'products_id=' . $_GET['products_id']));
    }
  } else {
    $_SESSION['check_valid'] = 'true';
  }

```

**Comment by jodsclass** [comment]
Have updated to the beta on my ZC version 1.5.6c and can confirm points 1-3 are correct. Without the commented out section in /includes/init_includes/init_sanitize.php it returns a 302 => 404 redirect loop (which google seems to dislike but seems to be the standard way zen deals with it). With the recheck redirect line commented out (line 140 of /includes/init_includes/init_sanitize.php in ZC 1.5.6c)  it returns a straight 404 which google prefers.

I'll stick with the core comment unless it can be done more elegantly within the USU plugin to override the standard ZC function).

**Comment by lat9** [comment]
Thanks for that confirmation, @jodsclass; I'll hold off for a day or so before 'pulling the trigger' on the v3.0.9 release.
